services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    volumes:
      - homepage-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - 'HOMEPAGE_ALLOWED_HOSTS=*'

volumes:
  homepage-config: {}
