# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # dns ports
      - "53:53/tcp"
      - "53:53/udp"
      # http/s ports
      # Uncomment the line below if you want to access the web interface on port 8080
      # - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
    volumes:
      - '/mnt/RemoteVolumes/etc-pihole:/etc/pihole'
    restart: unless-stopped