services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - resilio-config:/config
      - resilio-sync-content:/sync    # “Default folder” root in the UI
    ports:
      - "8888:8888"
      - "55555:55555/udp"
    restart: unless-stopped

volumes:
  resilio-config: {}

  resilio-sync-content:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//${CIFS_HOST}/${CIFS_SHARE}/resilio-sync-content"
      o: "username=${CIFS_USER},password=${CIFS_PASS},vers=3.0,uid=1000,gid=1000,iocharset=utf8,file_mode=0775,dir_mode=0775,noperm"
