services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=Etc/UTC
    volumes:
      - resilio-config:/config                  # local config (fast, safe for DB & settings)
      - resilio-sync-content:/sync              # mapped to CIFS share for synced folders
    ports:
      - "8888:8888"
      - "55555:55555/udp"
    restart: unless-stopped

volumes:
  resilio-config: {}

  resilio-sync-content:
    driver: local
    driver_opts:
      type: cifs
      o: username=${CIFS_USER},password=${CIFS_PASS},vers=3.0
      device: "//${CIFS_HOST}/${CIFS_SHARE}/resilio-sync-content"
