services:
  resilio-sync:
    image: resilio/sync:latest
    container_name: resilio-sync
    volumes:
      - resilio-sync:/mnt/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped

volumes:
  resilio-sync:
    driver: local
    driver_opts:
      type: cifs
      o: username=${CIFS_USER},password=${CIFS_PASS},vers=3.0
      device: "//${CIFS_HOST}/${CIFS_SHARE}/resilio-sync"
