services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    user: '0:0'  # Run as root user
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/RemoteVolumes/resilio-sync/config:/config
      - /mnt/RemoteVolumes/resilio-sync/downloads:/downloads
      - /mnt/RemoteVolumes/resilio-sync/data:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped