---
- name: Deploy Homepage configuration
  hosts: homepage
  become: true
  vars:
    homepage_volume_path: /var/lib/docker/volumes/homepage-config/_data
    local_config_path: ../homepage/config
  tasks:
    - name: Ensure homepage volume path exists
      ansible.builtin.file:
        path: "{{ homepage_volume_path }}"
        state: directory
        mode: "0755"

    - name: Create required directories inside homepage volume
      ansible.builtin.file:
        path: "{{ homepage_volume_path }}/{{ item.path }}"
        state: directory
        mode: "0755"
      loop: "{{ lookup('ansible.builtin.filetree', local_config_path, wantlist=True) }}"
      when: item.state == 'directory'

    - name: Copy homepage configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ homepage_volume_path }}/{{ item.path }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ lookup('ansible.builtin.filetree', local_config_path, wantlist=True) }}"
      when: item.state == 'file'
