- Homelab Docs:
    - Portainer:
        icon: portainer
        href: https://portainer.io/
    - AdGuard Documentation:
        icon: adguard
        href: https://adguard.com/kb/
- External Services:
    - Namecheap Account:
        icon: namecheap
        href: https://ap.www.namecheap.com/
