- Networking:
    - Pi-hole:
        icon: pi-hole
        href: https://homelab.local:8443/admin
        description: DNS sinkhole and ad blocker
    - Namecheap DDNS Updater:
        icon: mdi-dns
        href: https://www.namecheap.com/support/knowledgebase/article.aspx/29/11/how-to-use-the-namecheap-dynamic-dns-client
        description: Manage dynamic DNS credentials
- Media:
    - Plex Media Server:
        icon: plex
        href: https://app.plex.tv/desktop#!/media
        description: Stream media from the homelab library
    - qBittorrent-nox:
        icon: qbittorrent
        href: http://homelab.local:8080
        description: Manage BitTorrent downloads
- Storage & Sync:
    - Resilio Sync:
        icon: resilio-sync
        href: https://homelab.local:8888
        description: Peer-to-peer file synchronization
- Game Servers:
    - Crafty Controller:
        icon: minecraft
        href: https://homelab.local:7443
        description: Minecraft server manager and dashboard
- Reverse Proxy:
    - Nginx Proxy Manager:
        icon: nginx
        href: http://homelab.local:81
        description: SSL certificate and proxy management UI
- Monitoring & Tools:
    - Homepage:
        icon: home-assistant
        href: http://homelab.local:3000
        description: Homelab landing page
